import { promises as fs } from 'node:fs';
import { homedir } from 'node:os';
import { join } from 'node:path';
import {
  type ClaudeSettings,
  type SessionStartBlock,
  isCcppBlock,
  readSettings,
  writeSettings,
} from '../lib/claudeSettings.js';
import { UserError } from '../lib/errors.js';
import { writeFileAtomic } from '../lib/fsutil.js';
import { dim, green } from '../lib/term.js';

// Re-exports kept for backward compatibility with any callers still importing
// these names from install-hook.ts (e.g. uninstall-hook before the refactor).
export { isCcppBlock };

export type HookScope = 'user' | 'project';

export interface RunInstallHookOpts {
  /** Target scope: 'user' (`~/.claude/settings.json`) or 'project' (`./.claude/settings.json`). */
  scope: HookScope;
  /** Override the user-scope claude home (tests + --claude-home flag). */
  claudeHome?: string;
  /** Override the ccpp home where hook.sh gets materialised. Defaults to CCPP_HOME or ~/.ccpp. */
  ccppHome?: string;
  /** Override cwd for project-scope settings path. Defaults to process.cwd(). */
  cwd?: string;
  /** Append after an existing foreign SessionStart block instead of erroring. */
  chain?: boolean;
  /** Replace any existing SessionStart blocks with ccpp's. */
  force?: boolean;
  json?: boolean;
  quiet?: boolean;
}

export interface InstallHookResult {
  settingsPath: string;
  scriptPath: string;
  action: 'created' | 'updated' | 'chained' | 'replaced';
}

const ACTION_VERB: Record<InstallHookResult['action'], string> = {
  created: 'registered',
  updated: 'updated (already present)',
  chained: 'appended (chained after existing hook)',
  replaced: 'replaced existing hook',
};

/**
 * Body of the hook script. `ccpp install-hook` writes this to
 * `<ccppHome>/hook.sh` and points the Claude Code SessionStart entry at it.
 * Kept in sync with the human-readable copy at `scripts/hook.sh`.
 */
export const HOOK_SCRIPT_BODY = `#!/usr/bin/env bash
#
# ccpp SessionStart hook — generated by \`ccpp install-hook\`.
# MUST never block Claude Code — always exit 0, redirect errors to sync.log.

set +e

CCPP_HOME_DIR="\${CCPP_HOME:-\$HOME/.ccpp}"
LOG="\$CCPP_HOME_DIR/sync.log"
NOTICE="\$CCPP_HOME_DIR/last-hook-notice.txt"
mkdir -p "\$CCPP_HOME_DIR" 2>/dev/null

{
  ccpp sync --auto-accept --trigger hook
} >/dev/null 2>>"\$LOG"

# Surface a one-shot notice (e.g. agent changes that require a CC restart —
# see anthropics/claude-code#58592). Best-effort: missing file is fine.
if [ -s "\$NOTICE" ]; then
  cat "\$NOTICE" >&2
  rm -f "\$NOTICE"
fi

exit 0
`;

export function defaultCcppHome(): string {
  const env = process.env.CCPP_HOME;
  if (env && env.length > 0) return env;
  return join(homedir(), '.ccpp');
}

export function defaultClaudeHome(): string {
  return join(homedir(), '.claude');
}

export function settingsPathFor(opts: RunInstallHookOpts): string {
  if (opts.scope === 'project') {
    const cwd = opts.cwd ?? process.cwd();
    return join(cwd, '.claude', 'settings.json');
  }
  const home = opts.claudeHome ?? defaultClaudeHome();
  return join(home, 'settings.json');
}

async function writeHookScript(ccppHome: string): Promise<string> {
  await fs.mkdir(ccppHome, { recursive: true });
  const scriptPath = join(ccppHome, 'hook.sh');
  await writeFileAtomic(scriptPath, HOOK_SCRIPT_BODY);
  await fs.chmod(scriptPath, 0o755);
  return scriptPath;
}

/** POSIX-ish shell-safe single-quoted string. */
function shellQuote(s: string): string {
  if (/^[a-zA-Z0-9_\-./@+:]+$/.test(s)) return s;
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function makeCcppBlock(scriptPath: string): SessionStartBlock {
  // Matcher is the union of the three SessionStart sub-events Claude Code
  // emits: `startup` (fresh session), `resume` (continued from history),
  // and `clear` (after /clear). Syncing on all three keeps ~/.claude/
  // up to date whichever way the user enters a session.
  return {
    matcher: 'startup|resume|clear',
    hooks: [{ type: 'command', command: `bash ${shellQuote(scriptPath)}` }],
  };
}

export async function runInstallHook(opts: RunInstallHookOpts): Promise<InstallHookResult> {
  if (opts.chain === true && opts.force === true) {
    throw new UserError('ccpp install-hook: --chain and --force are mutually exclusive; pick one.');
  }

  const settingsPath = settingsPathFor(opts);
  const settings: ClaudeSettings = (await readSettings(settingsPath)) ?? {};
  const ccppHome = opts.ccppHome ?? defaultCcppHome();
  const scriptPath = await writeHookScript(ccppHome);
  const ccppBlock = makeCcppBlock(scriptPath);

  settings.hooks ??= {};
  settings.hooks.SessionStart ??= [];
  const blocks = settings.hooks.SessionStart;

  const existingCcppIdx = blocks.findIndex(isCcppBlock);
  let action: InstallHookResult['action'];

  if (existingCcppIdx >= 0) {
    blocks[existingCcppIdx] = ccppBlock;
    action = 'updated';
  } else if (blocks.length === 0) {
    blocks.push(ccppBlock);
    action = 'created';
  } else if (opts.force === true) {
    settings.hooks.SessionStart = [ccppBlock];
    action = 'replaced';
  } else if (opts.chain === true) {
    blocks.push(ccppBlock);
    action = 'chained';
  } else {
    throw new UserError(
      'another SessionStart hook is already configured — pass --chain to run both, or --force to overwrite',
    );
  }

  await writeSettings(settingsPath, settings);
  const result: InstallHookResult = { settingsPath, scriptPath, action };

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(result)}\n`);
  } else if (!opts.quiet) {
    process.stdout.write(`${green('✓')} ${ACTION_VERB[action]}\n`);
    process.stdout.write(`  ${dim('settings:')} ${settingsPath}\n`);
    process.stdout.write(`  ${dim('script:  ')} ${scriptPath}\n`);
  }

  return result;
}
