import { promises as fs } from 'node:fs';
import { homedir } from 'node:os';
import { dirname, join } from 'node:path';
import { dim, green } from '../lib/term.js';

class UserError extends Error {
  readonly exitCode = 1;
}

export type HookScope = 'user' | 'project';

export interface RunInstallHookOpts {
  /** Target scope: 'user' (`~/.claude/settings.json`) or 'project' (`./.claude/settings.json`). */
  scope: HookScope;
  /** Override the user-scope claude home (tests + --claude-home flag). */
  claudeHome?: string;
  /** Override the ccpp home where hook.sh gets materialised. Defaults to CCPP_HOME or ~/.ccpp. */
  ccppHome?: string;
  /** Override cwd for project-scope settings path. Defaults to process.cwd(). */
  cwd?: string;
  /** Append after an existing foreign SessionStart block instead of erroring. */
  chain?: boolean;
  /** Replace any existing SessionStart blocks with ccpp's. */
  force?: boolean;
  json?: boolean;
  quiet?: boolean;
}

export interface InstallHookResult {
  settingsPath: string;
  scriptPath: string;
  action: 'created' | 'updated' | 'chained' | 'replaced';
}

interface HookCommand {
  type: 'command';
  command: string;
}

interface SessionStartBlock {
  matcher?: string;
  hooks: HookCommand[];
}

interface ClaudeSettings {
  hooks?: {
    SessionStart?: SessionStartBlock[];
    [k: string]: unknown;
  };
  [k: string]: unknown;
}

/**
 * Body of the hook script. `ccpp install-hook` writes this to
 * `<ccppHome>/hook.sh` and points the Claude Code SessionStart entry at it.
 * Kept in sync with the human-readable copy at `scripts/hook.sh`.
 */
export const HOOK_SCRIPT_BODY = `#!/usr/bin/env bash
#
# ccpp SessionStart hook — generated by \`ccpp install-hook\`.
# MUST never block Claude Code — always exit 0, redirect errors to sync.log.

set +e

LOG="\${CCPP_HOME:-\$HOME/.ccpp}/sync.log"
mkdir -p "\$(dirname "\$LOG")" 2>/dev/null

{
  ccpp sync --auto-accept --trigger hook
} >/dev/null 2>>"\$LOG"

exit 0
`;

export function defaultCcppHome(): string {
  const env = process.env.CCPP_HOME;
  if (env && env.length > 0) return env;
  return join(homedir(), '.ccpp');
}

export function defaultClaudeHome(): string {
  return join(homedir(), '.claude');
}

export function settingsPathFor(opts: RunInstallHookOpts): string {
  if (opts.scope === 'project') {
    const cwd = opts.cwd ?? process.cwd();
    return join(cwd, '.claude', 'settings.json');
  }
  const home = opts.claudeHome ?? defaultClaudeHome();
  return join(home, 'settings.json');
}

export function isCcppBlock(block: SessionStartBlock): boolean {
  return block.hooks.some((h) => h.type === 'command' && /\bccpp\b/.test(h.command));
}

async function readSettings(path: string): Promise<ClaudeSettings> {
  try {
    const text = await fs.readFile(path, 'utf8');
    return JSON.parse(text) as ClaudeSettings;
  } catch (err) {
    if ((err as NodeJS.ErrnoException).code === 'ENOENT') return {};
    throw new Error(`Failed to read ${path}: ${(err as Error).message}`);
  }
}

async function writeSettings(path: string, settings: ClaudeSettings): Promise<void> {
  await fs.mkdir(dirname(path), { recursive: true });
  await fs.writeFile(path, `${JSON.stringify(settings, null, 2)}\n`, 'utf8');
}

async function writeHookScript(ccppHome: string): Promise<string> {
  await fs.mkdir(ccppHome, { recursive: true });
  const scriptPath = join(ccppHome, 'hook.sh');
  await fs.writeFile(scriptPath, HOOK_SCRIPT_BODY, { mode: 0o755 });
  return scriptPath;
}

/** POSIX-ish shell-safe single-quoted string. */
function shellQuote(s: string): string {
  if (/^[a-zA-Z0-9_\-./@+:]+$/.test(s)) return s;
  return `'${s.replace(/'/g, `'\\''`)}'`;
}

function makeCcppBlock(scriptPath: string): SessionStartBlock {
  return {
    matcher: 'startup|resume|clear',
    hooks: [{ type: 'command', command: `bash ${shellQuote(scriptPath)}` }],
  };
}

export async function runInstallHook(opts: RunInstallHookOpts): Promise<InstallHookResult> {
  if (opts.chain === true && opts.force === true) {
    throw new UserError('ccpp install-hook: --chain and --force are mutually exclusive; pick one.');
  }

  const settingsPath = settingsPathFor(opts);
  const settings = await readSettings(settingsPath);
  const ccppHome = opts.ccppHome ?? defaultCcppHome();
  const scriptPath = await writeHookScript(ccppHome);
  const ccppBlock = makeCcppBlock(scriptPath);

  settings.hooks ??= {};
  settings.hooks.SessionStart ??= [];
  const blocks = settings.hooks.SessionStart;

  const existingCcppIdx = blocks.findIndex(isCcppBlock);
  let action: InstallHookResult['action'];

  if (existingCcppIdx >= 0) {
    blocks[existingCcppIdx] = ccppBlock;
    action = 'updated';
  } else if (blocks.length === 0) {
    blocks.push(ccppBlock);
    action = 'created';
  } else if (opts.force === true) {
    settings.hooks.SessionStart = [ccppBlock];
    action = 'replaced';
  } else if (opts.chain === true) {
    blocks.push(ccppBlock);
    action = 'chained';
  } else {
    throw new UserError(
      'another SessionStart hook is already configured — pass --chain to run both, or --force to overwrite',
    );
  }

  await writeSettings(settingsPath, settings);
  const result: InstallHookResult = { settingsPath, scriptPath, action };

  if (opts.json) {
    process.stdout.write(`${JSON.stringify(result)}\n`);
  } else if (!opts.quiet) {
    const verb =
      action === 'created'
        ? 'registered'
        : action === 'updated'
          ? 'updated (already present)'
          : action === 'chained'
            ? 'appended (chained after existing hook)'
            : 'replaced existing hook';
    process.stdout.write(`${green('✓')} ${verb}\n`);
    process.stdout.write(`  ${dim('settings:')} ${settingsPath}\n`);
    process.stdout.write(`  ${dim('script:  ')} ${scriptPath}\n`);
  }

  return result;
}
